package tfg.ucav.model.solicitudes;
// Generated 01-may-2019 20:02:45 by Hibernate Tools 4.3.1



/**
 * SolicitudDetalle generated by hbm2java
 */
public class SolicitudDetalle  implements java.io.Serializable {


     private Integer id;
     private Solicitudes solicitudes;
     private int idCurso;
     private String estudiosAportados;
     private String centroProcedencia;
     private boolean primeraVez;
     private boolean repiteCurso;
     private boolean trasladoMatricula;
     private boolean exentoSeguro;
     private String NExpediente;

    public SolicitudDetalle() {
    }

	
    public SolicitudDetalle(Solicitudes solicitudes, int idCurso, String estudiosAportados, boolean primeraVez, boolean repiteCurso, boolean trasladoMatricula, boolean exentoSeguro) {
        this.solicitudes = solicitudes;
        this.idCurso = idCurso;
        this.estudiosAportados = estudiosAportados;
        this.primeraVez = primeraVez;
        this.repiteCurso = repiteCurso;
        this.trasladoMatricula = trasladoMatricula;
        this.exentoSeguro = exentoSeguro;
    }
    public SolicitudDetalle(Solicitudes solicitudes, int idCurso, String estudiosAportados, String centroProcedencia, boolean primeraVez, boolean repiteCurso, boolean trasladoMatricula, boolean exentoSeguro, String NExpediente) {
       this.solicitudes = solicitudes;
       this.idCurso = idCurso;
       this.estudiosAportados = estudiosAportados;
       this.centroProcedencia = centroProcedencia;
       this.primeraVez = primeraVez;
       this.repiteCurso = repiteCurso;
       this.trasladoMatricula = trasladoMatricula;
       this.exentoSeguro = exentoSeguro;
       this.NExpediente = NExpediente;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Solicitudes getSolicitudes() {
        return this.solicitudes;
    }
    
    public void setSolicitudes(Solicitudes solicitudes) {
        this.solicitudes = solicitudes;
    }
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }
    public String getEstudiosAportados() {
        return this.estudiosAportados;
    }
    
    public void setEstudiosAportados(String estudiosAportados) {
        this.estudiosAportados = estudiosAportados;
    }
    public String getCentroProcedencia() {
        return this.centroProcedencia;
    }
    
    public void setCentroProcedencia(String centroProcedencia) {
        this.centroProcedencia = centroProcedencia;
    }
    public boolean isPrimeraVez() {
        return this.primeraVez;
    }
    
    public void setPrimeraVez(boolean primeraVez) {
        this.primeraVez = primeraVez;
    }
    public boolean isRepiteCurso() {
        return this.repiteCurso;
    }
    
    public void setRepiteCurso(boolean repiteCurso) {
        this.repiteCurso = repiteCurso;
    }
    public boolean isTrasladoMatricula() {
        return this.trasladoMatricula;
    }
    
    public void setTrasladoMatricula(boolean trasladoMatricula) {
        this.trasladoMatricula = trasladoMatricula;
    }
    public boolean isExentoSeguro() {
        return this.exentoSeguro;
    }
    
    public void setExentoSeguro(boolean exentoSeguro) {
        this.exentoSeguro = exentoSeguro;
    }
    public String getNExpediente() {
        return this.NExpediente;
    }
    
    public void setNExpediente(String NExpediente) {
        this.NExpediente = NExpediente;
    }




}


