package tfg.ucav.model.solicitudes;
// Generated 05-may-2019 18:06:09 by Hibernate Tools 4.3.1



/**
 * SolicitudDocumentosId generated by hbm2java
 */
public class SolicitudDocumentosId  implements java.io.Serializable {


     private int idDocumento;
     private int idSolicitud;

    public SolicitudDocumentosId() {
    }

    public SolicitudDocumentosId(int idDocumento, int idSolicitud) {
       this.idDocumento = idDocumento;
       this.idSolicitud = idSolicitud;
    }
   
    public int getIdDocumento() {
        return this.idDocumento;
    }
    
    public void setIdDocumento(int idDocumento) {
        this.idDocumento = idDocumento;
    }
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SolicitudDocumentosId) ) return false;
		 SolicitudDocumentosId castOther = ( SolicitudDocumentosId ) other; 
         
		 return (this.getIdDocumento()==castOther.getIdDocumento())
 && (this.getIdSolicitud()==castOther.getIdSolicitud());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDocumento();
         result = 37 * result + this.getIdSolicitud();
         return result;
   }   


}


