package tfg.ucav.model.configuracion.cursos;
// Generated 05-may-2019 18:06:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer idCurso;
     private String nombre;
     private Set solicitudDetalles = new HashSet(0);

    public Curso() {
    }

	
    public Curso(String nombre) {
        this.nombre = nombre;
    }
    public Curso(String nombre, Set solicitudDetalles) {
       this.nombre = nombre;
       this.solicitudDetalles = solicitudDetalles;
    }
   
    public Integer getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getSolicitudDetalles() {
        return this.solicitudDetalles;
    }
    
    public void setSolicitudDetalles(Set solicitudDetalles) {
        this.solicitudDetalles = solicitudDetalles;
    }




}


