package tfg.ucav.model.configuracion.cursos;
// Generated 02-may-2019 8:28:30 by Hibernate Tools 4.3.1



/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer idCurso;
     private String nombre;

    public Curso() {
    }

    public Curso(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


