package tfg.ucav.model.usuarios;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of USER.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_USER. */
	private Integer idUser;

	/** NOMBRE. */
	private String nombre;

	/** APELLIDOS. */
	private String apellidos;

	/** EMAIL. */
	private String email;

	/** PASSWORD. */
	private String password;

	/** CREATE_TIME. */
	private Date createTime;

	/** ROLE. */
	private Role role;

	/** The set of SOLICITUD. */
	//private Set<Solicitud> solicitudSet;

	/**
	 * Constructor.
	 */
	public User() {
		//this.solicitudSet = new HashSet<Solicitud>();
                //Set default create time
                this.createTime = new Date();
               
	}

	/**
	 * Set the ID_USER.
	 * 
	 * @param idUser
	 *            ID_USER
	 */
	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	/**
	 * Get the ID_USER.
	 * 
	 * @return ID_USER
	 */
	public Integer getIdUser() {
		return this.idUser;
	}

	/**
	 * Set the NOMBRE.
	 * 
	 * @param nombre
	 *            NOMBRE
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the NOMBRE.
	 * 
	 * @return NOMBRE
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the APELLIDOS.
	 * 
	 * @param apellidos
	 *            APELLIDOS
	 */
	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	/**
	 * Get the APELLIDOS.
	 * 
	 * @return APELLIDOS
	 */
	public String getApellidos() {
		return this.apellidos;
	}

	/**
	 * Set the EMAIL.
	 * 
	 * @param email
	 *            EMAIL
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the EMAIL.
	 * 
	 * @return EMAIL
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the PASSWORD.
	 * 
	 * @param password
	 *            PASSWORD
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the PASSWORD.
	 * 
	 * @return PASSWORD
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the CREATE_TIME.
	 * 
	 * @param createTime
	 *            CREATE_TIME
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the CREATE_TIME.
	 * 
	 * @return CREATE_TIME
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the ROLE.
	 * 
	 * @param role
	 *            ROLE
	 */
	public void setRoles(Role role) {
		this.role = role;
	}

	/**
	 * Get the ROLE.
	 * 
	 * @return ROLE
	 */
	public Role getRole() {
		return this.role;
	}

	/**
	 * Set the set of the SOLICITUD.
	 * 
	 * @param solicitudSet
	 *            The set of SOLICITUD
	 */
        /*
	public void setSolicitudSet(Set<Solicitud> solicitudSet) {
		this.solicitudSet = solicitudSet;
	}
        */
	/**
	 * Add the SOLICITUD.
	 * 
	 * param solicitud
	 *            SOLICITUD
	 */
        /*
	public void addSolicitud(Solicitud solicitud) {
		this.solicitudSet.add(solicitud);
	}
*/
	/*
	/**
	 * Get the set of the SOLICITUD.
	 * 
	 * @return The set of SOLICITUD
	 */
        /*
	public Set<Solicitud> getSolicitudSet() {
		return this.solicitudSet;
	}
*/
	/*
	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idUser == null) ? 0 : idUser.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		User other = (User) obj;
		if (idUser == null) {
			if (other.idUser != null) {
				return false;
			}
		} else if (!idUser.equals(other.idUser)) {
			return false;
		}
		return true;
	}

}
