package tfg.ucav.model.configuracion.provincias;
// Generated 01-may-2019 20:02:45 by Hibernate Tools 4.3.1



/**
 * Provincias generated by hbm2java
 */
public class Provincias  implements java.io.Serializable {


     private Integer idProvincia;
     private String nombre;

    public Provincias() {
    }

    public Provincias(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(Integer idProvincia) {
        this.idProvincia = idProvincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


